# Generated by Django 5.0 on 2025-05-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ids", models.CharField(max_length=100, verbose_name="아이디")),
                ("usernames", models.CharField(max_length=100, verbose_name="이름")),
                ("password", models.CharField(max_length=100, verbose_name="비밀번호")),
                ("email", models.CharField(max_length=100, verbose_name="이메일")),
                ("phone", models.CharField(max_length=100, verbose_name="전화번호")),
                ("cnts", models.IntegerField(default=0, verbose_name="방문수")),
                ("first_dates", models.CharField(max_length=20, verbose_name="가입일")),
                ("first_ips", models.CharField(max_length=20, verbose_name="가입IP")),
            ],
        ),
    ]
