# Generated by Django 3.2.13 on 2022-11-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moviename',
        ),
    ]
